# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Check, Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run cppcheck
      uses: deep5050/cppcheck-action@v3.0

  build-and-test:
    name: Build and Test

    runs-on: ubuntu-latest
    needs: check

    steps:
    - uses: actions/checkout@v3

    - name: Run setup-linux.sh
      run: bash ${{github.workspace}}/setup-linux.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

