name: Doxygen

on:
  push:
    branches: [ "main" ]

  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  doxygen:
    name: Doxygen

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: ${{github.workspace}}/Modules/Core
        doxyfile-path: ${{github.workspace}}/Doxyfile

